# Project name: NewPerspective
# # Description: Assesses social issues that students should look into for volunteer work.
# # Filename: part3s_controller.rb
# # Description: Controller for the Part 3 (Gender) of the questionaire.
# # Last modified on: April 26, 2020

class Part3sController < ApplicationController
  before_action :set_part3, only: [:show, :edit, :update, :destroy]

  # GET /part3s
  # GET /part3s.json
  def index
    @part3s = Part3.all
  end

  # GET /part3s/1
  # GET /part3s/1.json
  def show
  end

  # GET /part3s/new
  def new
    @part3 = Part3.new
  end

  # GET /part3s/1/edit
  def edit
  end

  # POST /part3s
  # POST /part3s.json
  #
  # Originally generated by a Scaffold. Modified where noted.
  def create
    #Modification; if user gives an empty submission, stay on the page
    if params[:part3] == nil
      redirect_to new_part3_url
      return
    end

    @part3 = Part3.new(part3_params)
    @part3s = Part3.all

    respond_to do |format|
      if @part3.save
        format.html { redirect_to new_part4_path, notice: 'Part3 was successfully created.' }
        format.json { render :show, status: :created, location: @part3 }
      else
        format.html { render :new }
        format.json { render json: @part3.errors, status: :unprocessable_entity }
      end
    end

    #Modification; Delete previously submitted questionaire to manage database.
    if @part3s.length() > 1
      @part3s[@part3s.length() - 2].destroy()
    end
  end

  # PATCH/PUT /part3s/1
  # PATCH/PUT /part3s/1.json
  def update
    respond_to do |format|
      if @part3.update(part3_params)
        format.html { redirect_to results_index_url, notice: 'Part3 was successfully updated.' }
        format.json { render :show, status: :ok, location: @part3 }
      else
        format.html { render :edit }
        format.json { render json: @part3.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /part3s/1
  # DELETE /part3s/1.json
  def destroy
    @part3.destroy
    respond_to do |format|
      format.html { redirect_to results_index_url, notice: 'Part3 was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #   Function: name ()
  #   #
  #   #     Parameters:
  #   #
  #   #     Pre-condition: Program needs the name of the topic associated with Part 3 of the questionaire
  #   #
  #   #     Post-condition: The name of the topic is returned.
  def name
    return "Gender"
  end

# Function: information ()
#     
# Parameters:
#         
# Pre-condition: Program needs a summary of the topic associated with Part 3 of the questionaire
#             
# Post-condition: The summary of the topic is returned.
  def information
    return "Gender Issues are interdisciplinary and cross-national in scope
    focusing on gender and gender equality. Gender issues include all aspects
    and concerns related to women’s and men’s lives and situation in society,
    to the way they interrelate, their differences in access to and use of
    resources, their activities, and how they react to changes, interventions
    and policies. Gender equality is the goal, while gender neutrality and
    gender equity are practices and ways of thinking that help in achieving the goal.
    Gender equality is more than equal representation, it is strongly tied to women's rights"
  end

# Function: sourceTitle ()
#     
# Parameters:
#         
# Pre-condition: Program needs the names of the provided sources.
#             
# Post-condition: An array of the names of the sources are returned.
  def sourceTitle
    titles = ["Examples of Male Privilege", "Gender Issues", "What is Male Privilege"]
    return titles
  end

  # Function: sourceTitle ()
  #     
  # Parameters:
  #         
  # Pre-condition: Program needs links to the provided sources.
  #             
  # Post-condition: An array of the links to the sources are returned.
  def sources
    cite = ["https://everydayfeminism.com/2016/02/160-examples-of-male-privilege/", "https://www.apa.org/research/action/gender", "http://www.academicroom.com/topics/what-is-male-privilege"]
    return cite
  end

# Function: countTotal ()
#     
# Parameters:
#         
# Pre-condition: Program needs to the total score the user got based on their answers.
#             
# Post-condition: The calculated total is returned.
  def countTotal
    @part3s = Part3.all
    total = @part3s[@part3s.length() - 1].ans1 + @part3s[@part3s.length() - 1].ans2 +
    @part3s[@part3s.length() - 1].ans3 + @part3s[@part3s.length() - 1].ans4 + @part3s[@part3s.length() - 1].ans5 +
      @part3s[@part3s.length() - 1].ans6 + @part3s[@part3s.length() - 1].ans7 +
      @part3s[@part3s.length() - 1].ans8 + @part3s[@part3s.length() - 1].ans9 + @part3s[@part3s.length() - 1].ans10
    return total
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part3
      @part3 = Part3.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def part3_params
      params.require(:part3).permit(:ans1, :ans2, :ans3, :ans4, :ans5, :ans6, :ans7, :ans8, :ans9, :ans10)
    end
end
